from colorama import init, Fore, Back, Style # Import coloram for UI
import random

init(autoreset=True)

def cd(fore1,back1,style1,char):
	# Used to print individual characters using the colorama module
	# This saves you from using b'\xb0'.decode('cp437') over and over again.
	match fore1:
		case 'bl':
			fore1 = Fore.BLACK
		case 'r':
			fore1 = Fore.RED
		case 'g':
			fore1 = Fore.GREEN
		case 'y':
			fore1 = Fore.YELLOW
		case 'b':
			fore1 = Fore.BLUE
		case 'm':
			fore1 = Fore.MAGENTA
		case 'c':
			fore1 = Fore.CYAN
		case 'w':
			fore1 = Fore.WHITE
		case '':
			pass
	match back1:
		case 'bl':
			back1 = Back.BLACK
		case 'r':
			back1 = Back.RED
		case 'g':
			back1 = Back.GREEN
		case 'y':
			back1 = Back.YELLOW
		case 'b':
			back1 = Back.BLUE
		case 'm':
			back1 = Back.MAGENTA
		case 'c':
			back1 = Back.CYAN
		case 'w':
			back1 = Back.WHITE
		case '':
			pass
	match style1:
		case 'd':
			style1 = Style.DIM
		case 'n':
			style1 = Style.NORMAL
		case 'b':
			style1 = Style.BRIGHT
		case 'r':
			style1 = Style.RESET_ALL
		case '':
			pass

	'''
	Characters from https://en.wikipedia.org/wiki/Code_page_437

	░ ▒ ▓ █ ▄ ▀ ■ ▌▐ │ ┤ ╡ ╢ ╖ ╕ ╣ ║ ╗ ╝ ╜ ╛ ┐ └ ┴ ┬ ├ ─ ┼ ╞ ╟ ╚ ╔ ╩ ╦ ╠ ═ ╬ ╧ ╨ ╤ ╥ ╙ ╘ ╒ ╓ ╫ ╪ ┘ ┌
	· ∙ ° ° • . * 

	┌─┬─┐
	│ │ │
	├─┼─┤
	└─┴─┘
	'''
	print(fore1+back1+style1+char,end="")

def mainscreen():
	rand = random.randrange(1,3)
	match rand:
		case 1:
			mainscreen1()
		case 2:
			mainscreen2()

def mainscreen1():
	print(Fore.YELLOW+Style.BRIGHT+"""\
   ______________    ____     __________  ________ __
  / ___/_  __/   |  / __ \   /_  __/ __ \/ ____/ //_/
  \__ \ / / / /| | / /_/ /    / / / /_/ / __/ / ,<   
 ___/ // / / ___ |/ _, _/    / / / _, _/ /___/ /| |  
/____//_/ /_/  |_/_/ |_|    /_/ /_/ |_/_____/_/ |_|
	""")
	print(Fore.MAGENTA+Style.BRIGHT+"[Pause]")
	input("")

def mainscreen2():
	#
	# Row 1
	#
	cd('bl','bl','n',"  ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n',"   ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n',"   ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n',"  ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n',"         ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n',"    ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',"*") #star
	cd('bl','bl','n',"   ")
	# ░ ▒ ▓ █ ▄ ▀ ■ ▌▐
	cd('b','bl','b',"▀")
	cd('b','b','b',"▄")
	cd('b','b','b',"░░░░▒░░▒▒░")
	cd('b','b','d',"  ")
	cd('b','b','b',"▓")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	print("",end="\r\n")
	#
	# Row 2
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".")
	# ░ ▒ ▓ █ ▄ ▀ ■ ▌▐
	cd('b','bl','b',"▀")
	cd('b','b','b',"▄")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"▒")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','b',"▓")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	print("",end="\r\n")
	#
	# Row 3
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('b','bl','b',"▀")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"▒")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','b',"▓")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"▒")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"▒")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"▓")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	print("",end="\r\n")
	#
	# Row 4
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"█")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','bl','b',"▄")
	cd('bl','bl','n'," ")
	cd('w','bl','b',"▄")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','bl','b',"▄")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','bl','b',"▄")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('b','bl','b',"▀")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"▓")
	cd('b','b','b',"▒")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	print("",end="\r\n")
	#
	# Row 5
	#
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('w','w','b',"█")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('b','bl','b',"▀")
	cd('b','bl','b',"▀")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"▒")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	print("",end="\r\n")
	#
	# Row 6
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','bl','b',"▄")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','w','b',"▀")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('b','bl','b',"▀")
	cd('b','bl','b',"▀")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"▒")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"▒")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	print("",end="\r\n")
	#
	# Row 7
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',"*") # star
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('b','bl','b',"▀")
	cd('b','bl','b',"▀")
	cd('b','bl','b',"▀")
	cd('b','bl','b',"▀")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	cd('b','b','d'," ")
	cd('b','b','d'," ")
	cd('b','b','b',"░")
	print("",end="\r\n")
	#
	# Row 8
	#
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','bl','d',".") # star
	cd('w','w','b',"█")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"▄")
	cd('w','w','b',"▀")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"▄")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',"*") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('b','bl','b',"▀")
	cd('b','bl','b',"▀")
	cd('b','bl','b',"▀")
	cd('b','bl','b',"▀")
	cd('b','bl','b',"▀")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	cd('b','b','b',"▄")
	print("",end="\r\n")
	#
	# Row 9
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	print("",end="\r\n")
	#
	# Row 10
	#
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','bl','b',"▄")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','bl','b',"▄")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','bl','b',"▄")
	cd('bl','bl','n'," ")
	cd('w','bl','b',"▄")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','bl','b',"▄")
	cd('w','bl','d',"*") # star
	cd('r','bl','b',"▄")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','bl','b',"▄")
	cd('bl','bl','n'," ")
	cd('r','bl','b',"▄")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','bl','b',"▄")
	cd('bl','bl','n'," ")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','bl','b',"▄")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	print("",end="\r\n")
	#
	# Row 11
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','d',"═")
	cd('b','bl','d',"═")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','d',"═")
	cd('b','bl','d',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','d',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','d',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('b','bl','d',"═")
	cd('b','bl','d',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('w','bl','b',"▐")
	cd('w','bl','d',"▌")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	print("",end="\r\n")
	#
	# Row 12
	#
	cd('bl','bl','n'," ")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('w','w','b',"█")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('w','w','b',"█")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','bl','b',"▄")
	cd('b','bl','d',"═")
	cd('w','bl','d',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','bl','b',"▄")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('r','bl','b',"▄")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','bl','d',"▀")
	cd('b','bl','d',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('r','bl','b',"▄")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','bl','d',"▀")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('w','w','b',"█")
	cd('w','w','d',"█")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	print("",end="\r\n")
	#
	# Row 13
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('b','bl','d',"═")
	cd('b','bl','d',"═")
	cd('w','w','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('r','r','b',"█")
	cd('b','bl','d',"═")
	cd('b','bl','d',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"═")
	cd('b','bl','b',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('w','w','b',"█")
	cd('w','w','d',"█")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	cd('b','bl','d',"─")
	print("",end="\r\n")
	#
	# Row 14
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','bl','b',"▄")
	cd('w','w','b',"▀")
	cd('w','bl','b',"▄")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('bl','bl','n'," ")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"▄")
	cd('w','w','b',"▀")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('bl','bl','n'," ")
	cd('r','bl','d',"▀")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('r','bl','d',"▀")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('r','r','b',"▀")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"▌")
	cd('w','w','d',"█")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	print("",end="\r\n")
	#
	# Row 15
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"▀")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','n',"╔")
	cd('w','w','b',"═")
	cd('w','w','b',"═")
	cd('w','w','b',"═")
	cd('w','w','b',"═")
	cd('w','w','d'," ")
	cd('w','w','d'," ")
	cd('w','bl','d',"╗")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	print("",end="\r\n")
	#
	# Row 15
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"┌")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','w','b',"▄")
	cd('w','w','b',"▄")
	cd('w','w','b',"▄")
	cd('w','w','b',"▄")
	cd('w','w','b',"▄")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"▄")
	cd('bl','bl','b'," ")
	print("",end="\r\n")
	#
	# Row 16
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"┌")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"▄")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','bl','b',"█")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	print("",end="\r\n")
	#
	# Row 17
	#
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',"▀")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"█")
	cd('w','w','b',"▀")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"▓")
	print("",end="\r\n")
	#
	# Row 18
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"├")
	cd('w','bl','b',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"┼")
	cd('w','bl','b',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"┼")
	cd('w','bl','b',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"┼")
	cd('w','bl','d',"─")
	cd('w','bl','b',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"┼")
	cd('w','bl','d',"─")
	cd('w','bl','b',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"┼")
	cd('w','bl','d',"─")
	cd('w','bl','b',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"┼")
	cd('w','bl','d',"─")
	cd('w','bl','b',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"┼")
	cd('w','bl','d',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"┼")
	cd('w','bl','d',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"┼")
	cd('w','bl','d',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"┼")
	cd('w','bl','d',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"─")
	cd('w','bl','d',"┼")
	cd('bl','bl','d'," ")
	print("",end="\r\n")
	#
	# Row 19
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','b',"▀")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','w','d',"█")
	cd('w','bl','d',"▓")
	print("",end="\r\n")
	#
	# Row 20
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"▓")
	print("",end="\r\n")
	#
	# Row 21
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"▀")
	cd('w','bl','d',"▀")
	cd('w','bl','d',".") # star
	print("",end="\r\n")
	#
	# Row 22
	#
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"*") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('w','bl','b',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',"╒")
	cd('w','bl','d',"▌")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"█")
	cd('w','bl','d',"▓")
	cd('w','bl','d',"▐")
	cd('w','bl','d',"╕")
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	cd('w','bl','d',".") # star
	cd('bl','bl','n'," ")
	cd('bl','bl','n'," ")
	print("",end="\r\n")
	print(Fore.MAGENTA+Style.BRIGHT+"[Pause]")
	input("")
	
def characters():
	print("░ ▒ ▓ █ ▄ ▀ ■ ▌▐ │ ┤ ╡ ╢ ╖ ╕ ╣ ║ ╗ ╝ ╜ ╛ ┐ └ ┴ ┬ ├ ─ ┼ ╞ ╟ ╚ ╔ ╩ ╦ ╠ ═ ╬ ╧ ╨ ╤ ╥ ╙ ╘ ╒ ╓ ╫ ╪ ┘ ┌	· ∙ ° ° • . * ")

def shipyards():

	#
	# Row 1
	#
	cd('b','bl','b','┌──────────────────────────────────┐')
	print("",end="\r\n")
	#
	# Row 2
	#
	cd('b','bl','b','│')
	cd('w','bl','b','═╬═╬═╬═╬═╬═╬═╬')
	cd('r','r','b','█')
	cd('w','bl','d',".  ") # star
	cd('w','bl','b',".") # star
	cd('w','bl','d',". ") # star
	cd('w','bl','b',". ") # star
	cd('w','bl','d',".  .") # star
	cd('w','bl','b'," .  ") # star
	cd('w','bl','d'," . ") # star
	cd('b','bl','b','│  ────────────────────────────────────────')
	print("",end="\r\n")
	#
	# Row 3
	#
	cd('b','bl','b','│')
	cd('w','bl','d','═╬═╬═╬═╬═╬═╬═╬')
	cd('r','r','d','█')
	cd('w','bl','d'," .  ") # star
	cd('b','bl','d',". ") # star
	cd('w','bl','d',".  ") # star
	cd('w','bl','b',".    ") # star
	cd('w','bl','d',".  ") # star
	cd('w','bl','d','│')
	cd('r','bl','b',':')
	cd('b','bl','b','│')
	cd('w','bl','n','   As you enter the Federation Shipyards,')
	print("",end="\r\n")
	#
	# Row 4
	#
	cd('b','bl','b','│')
	cd('w','bl','d','═╬═╬═╬═╬═╬═╬═╬')
	cd('r','r','d','█')
	cd('w','bl','d'," .") # star
	cd('w','bl','b'," .") # star
	cd('w','bl','d'," .  .   ") # star
	cd('w','bl','b'," .") # star
	cd('w','bl','d'," . ") # star
	cd('w','bl','d','│')
	cd('w','bl','b','│')
	cd('b','bl','b','│')
	cd('w','bl','n','   you pass by  row after  row of  ships.')
	print("",end="\r\n")
	#
	# Row 5
	#
	cd('b','bl','b','│')
	cd('w','bl','d','═')
	cd('b','b','d','│')
	cd('w','b','b','Federation')
	cd('b','bl','d','│')
	cd('w','bl','d','╬')
	cd('r','r','d','█')
	cd('w','bl','d'," .    .   ") # star
	cd('r','bl','b',".")
	cd('w','bl','b',". ") # star
	cd('w','bl','d',".") # star
	cd('r','bl','b',". ")
	cd('w','w','d','   ')
	cd('b','bl','b','│')
	cd('w','bl','n','   Most  of  them are  shiny and  new but')
	print("",end="\r\n")
	#
	# Row 6
	#
	cd('b','bl','b','│')
	cd('w','bl','d','═')
	cd('b','b','d','│')
	cd('w','b','b','Shipyards')
	cd('b','b','b','.')
	cd('b','bl','d','│')
	cd('w','bl','d','╬')
	cd('r','r','d','█')
	cd('bl','bl','d','█')
	cd('w','bl','d','▄')
	cd('w','w','b','▄▄▄')
	cd('w','bl','b','▄')
	cd('w','c','b','▄▄')
	cd('w','bl','b','▄─')
	cd('w','bl','d','▐')
	cd('w','bl','b','▄')
	cd('w','c','b','▄')
	cd('w','bl','b','▄')
	cd('w','bl','d','▌')
	cd('bl','bl','b',' ')
	cd('w','bl','d','▐')
	cd('c','w','d','■')
	cd('bl','w','d','█')
	cd('b','bl','b','│')
	cd('w','bl','n','   some show signs of use.  You recognize') 
	print("",end="\r\n")
	#
	# Row 7
	#
	cd('b','bl','b','│')
	cd('w','bl','d','═')
	cd('b','b','d','│')
	cd('r','b','b','═══────═══')
	cd('b','bl','d','│')
	cd('w','bl','d','╬')
	cd('r','r','d','█')
	cd('b','b','b','██')
	cd('w','b','b','╜╜')
	cd('b','b','b','████')
	cd('w','b','b','└')
	cd('b','b','b','██')
	cd('w','b','b','┴┴┴')
	cd('b','b','b','█████')
	cd('b','bl','b','│')
	cd('w','bl','n','   the registrations on some of the older')
	'''
	Characters from https://en.wikipedia.org/wiki/Code_page_437

	░ ▒ ▓ █ ▄ ▀ ■ ▌▐ │ ┤ ╡ ╢ ╖ ╕ ╣ ║ ╗ ╝ ╜ ╛ ┐ └ ┴ ┬ ├ ─ ┼ ╞ ╟ ╚ ╔ ╩ ╦ ╠ ═ ╬ ╧ ╨ ╤ ╥ ╙ ╘ ╒ ╓ ╫ ╪ ┘ ┌
	· ∙ ° ° • . * 
	┌─┬─┐
	│ │ │
	├─┼─┤
	└─┴─┘
	'''
	print("",end="\r\n")
	#
	# Row 8
	#
	cd('b','bl','b','│')
	cd('w','bl','d','═╬═╬═╬═╬═╬═╬═╬')
	cd('r','r','d','█')
	cd('b','bl','b','▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
	cd('b','bl','b','│')
	cd('w','bl','n','   ships as craft you have seen  at other')
	print("",end="\r\n")
	#
	# Row 9
	#
	cd('b','bl','b','│')
	cd('w','bl','d','═╬═╬═╬═╬═╬═╬═╬')
	cd('r','r','d','█')
	cd('b','bl','d','▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓')
	cd('b','bl','b','│')
	cd('w','bl','n','   trading ports before.                ')
	print("",end="\r\n")
	#
	# Row 10
	#
	cd('b','bl','b','│')
	cd('w','bl','d','═╬═╬═╬═╬═╬═╬═╬')
	cd('r','r','d','█')
	cd('b','bl','d','░░░░░░░░░░░░░░░░░░░')
	cd('b','bl','b','│')
	cd('b','bl','b','  ────────────────────────────────────────')
	print("",end="\r\n")
	#
	# Row 11
	#
	cd('b','bl','b','└──────────────────────────────────┘')
	print("",end="\r\n")
