	#
	# Row 21
	#
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(244,0,"*", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,"*", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,"▀", '', False)
	art.cd(244,0,"▀", '', False)
	art.cd(244,0,"▀", '', False)
	art.cd(244,0,"▀", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"▓", 0, True)
	#
	# Row 22
	#
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,"*", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,"*", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(244,0,"▀", '', False)
	art.cd(244,0,"▀", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"▀", '', False)
	art.cd(244,0,"▀", '', False)
	art.cd(244,0,".", 0, True) # star
	#
	# Row 23
	#
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,"*", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,"*", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(255,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,"╒", '', False)
	art.cd(244,0,"▌", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"█", '', False)
	art.cd(244,0,"▓", '', False)
	art.cd(244,0,"▐", '', False)
	art.cd(244,0,"╕", '', False)
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", '', False)
	art.cd(244,0,".", '', False) # star
	art.cd(0,0," ", '', False)
	art.cd(0,0," ", 0, True)